import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "My first next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
        }}
      >
        <header style={{ textAlign: "center", color: "red" }}>Header</header>
        <main>{children}</main>
        <footer style={{ textAlign: "center", color: "red" }}>Footer</footer>
      </body>
    </html>
  );
}
